#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

# Allows visualising a 2D map generated by vehicles.

"""
Welcome to CARLA No-Rendering Mode Visualizer

    TAB          : toggle hero mode
    Mouse Wheel  : zoom in / zoom out
    Mouse Drag   : move map (map mode only)

    W            : throttle
    S            : brake
    AD           : steer
    Q            : toggle reverse
    Space        : hand-brake
    P            : toggle autopilot
    M            : toggle manual transmission
    ,/.          : gear up/down

    F1           : toggle HUD
    I            : toggle actor ids
    H/?          : toggle help
    ESC          : quit
"""

# ==============================================================================
# -- imports -------------------------------------------------------------------
# ==============================================================================

import os
import cv2

import carla
from carla import TrafficLightState as tls

import argparse
import logging
import datetime
import weakref
import math
import random

try:
    import pygame
    from pygame.locals import KMOD_CTRL
    from pygame.locals import KMOD_SHIFT
    from pygame.locals import K_COMMA
    from pygame.locals import K_DOWN
    from pygame.locals import K_ESCAPE
    from pygame.locals import K_F1
    from pygame.locals import K_LEFT
    from pygame.locals import K_PERIOD
    from pygame.locals import K_RIGHT
    from pygame.locals import K_SLASH
    from pygame.locals import K_SPACE
    from pygame.locals import K_TAB
    from pygame.locals import K_UP
    from pygame.locals import K_a
    from pygame.locals import K_d
    from pygame.locals import K_h
    from pygame.locals import K_i
    from pygame.locals import K_m
    from pygame.locals import K_p
    from pygame.locals import K_q
    from pygame.locals import K_s
    from pygame.locals import K_w
except ImportError:
    raise RuntimeError('cannot import pygame, make sure pygame package is installed')

import numpy as np

# from . import RoadOption
from agents.navigation.local_planner import RoadOption
from agents.tools.misc import is_within_distance, compute_distance

def is_within_distance_ahead(target_transform, current_transform, max_distance, degree=90.):
    """
    Check if a target object is within a certain distance in front of a reference object.

    :param target_transform: location of the target object
    :param current_transform: location of the reference object
    :param orientation: orientation of the reference object
    :param max_distance: maximum allowed distance
    :return: True if target object is within max_distance ahead of the reference object
    """
    target_vector = np.array([target_transform.location.x - current_transform.location.x, target_transform.location.y - current_transform.location.y])
    norm_target = np.linalg.norm(target_vector)

    # If the vector is too short, we can simply stop here
    if norm_target < 0.001:
        return True

    if norm_target > max_distance:
        return False

    fwd = current_transform.get_forward_vector()
    forward_vector = np.array([fwd.x, fwd.y])
    d_angle = math.degrees(math.acos(np.clip(np.dot(forward_vector, target_vector) / norm_target, -1., 1.)))

    return d_angle < degree

# ==============================================================================
# -- Constants -----------------------------------------------------------------
# ==============================================================================

MAP_SIZE = 320

# Colors

# We will use the color palette used in Tango Desktop Project (Each color is indexed depending on brightness level)
# See: https://en.wikipedia.org/wiki/Tango_Desktop_Project

COLOR_BUTTER_0 = pygame.Color(252, 233, 79)
COLOR_BUTTER_1 = pygame.Color(237, 212, 1)
COLOR_BUTTER_2 = pygame.Color(196, 160, 1)

COLOR_ORANGE_0 = pygame.Color(252, 175, 62)
COLOR_ORANGE_1 = pygame.Color(245, 121, 1)
COLOR_ORANGE_2 = pygame.Color(209, 92, 1)

COLOR_CHOCOLATE_0 = pygame.Color(233, 185, 110)
COLOR_CHOCOLATE_1 = pygame.Color(193, 125, 17)
COLOR_CHOCOLATE_2 = pygame.Color(143, 89, 2)

COLOR_CHAMELEON_0 = pygame.Color(138, 226, 52)
COLOR_CHAMELEON_1 = pygame.Color(115, 210, 22)
COLOR_CHAMELEON_2 = pygame.Color(78, 154, 6)

COLOR_SKY_BLUE_0 = pygame.Color(114, 159, 207)
COLOR_SKY_BLUE_1 = pygame.Color(52, 101, 164)
COLOR_SKY_BLUE_2 = pygame.Color(32, 74, 135)

COLOR_PLUM_0 = pygame.Color(173, 127, 168)
COLOR_PLUM_1 = pygame.Color(117, 80, 123)
COLOR_PLUM_2 = pygame.Color(92, 53, 102)

COLOR_SCARLET_RED_0 = pygame.Color(239, 41, 41)
COLOR_SCARLET_RED_1 = pygame.Color(204, 1, 1)
COLOR_SCARLET_RED_2 = pygame.Color(164, 1, 1)

COLOR_ALUMINIUM_0 = pygame.Color(238, 238, 236)
COLOR_ALUMINIUM_1 = pygame.Color(211, 215, 207)
COLOR_ALUMINIUM_2 = pygame.Color(186, 189, 182)
COLOR_ALUMINIUM_3 = pygame.Color(136, 138, 133)
COLOR_ALUMINIUM_4 = pygame.Color(85, 87, 83)
COLOR_ALUMINIUM_4_5 = pygame.Color(66, 62, 64)
COLOR_ALUMINIUM_5 = pygame.Color(46, 52, 54)


COLOR_WHITE = pygame.Color(255, 255, 255)
COLOR_BLACK = pygame.Color(0, 0, 0)

COLOR_TRAFFIC_RED = pygame.Color(255, 1, 1)
COLOR_TRAFFIC_YELLOW = pygame.Color(1, 255, 1)
COLOR_TRAFFIC_GREEN = pygame.Color(1, 1, 255)


# Module Defines
MODULE_WORLD = 'WORLD'
MODULE_HUD = 'HUD'
MODULE_INPUT = 'INPUT'

PIXELS_PER_METER = 4

MAP_DEFAULT_SCALE = 0.1
HERO_DEFAULT_SCALE = 1.0

PIXELS_AHEAD_VEHICLE = 120

# ==============================================================================
# -- Utils -----------------------------------------------------------
# ==============================================================================

def cart2polar(dx, dy):
    dx += 1e-5
    dy += 1e-5
    arctan = math.degrees(math.atan2(dy, dx))
    return arctan + {(1,1):0,(-1,1):180,(-1,-1):180,(1,-1):360}.get((dx/abs(dx), dy/abs(dy)))


def encode_orientation(o_yaw):
    yaw = o_yaw
    while yaw < 0:
        yaw += 360
    while yaw > 360:
        yaw -= 360

    r = g = b = 100 + int(yaw*155./360.)

    return pygame.Color(r, g, b)


def get_actor_display_name(actor, truncate=250):
    name = ' '.join(actor.type_id.replace('_', '.').title().split('.')[1:])
    return (name[:truncate - 1] + u'\u2026') if len(name) > truncate else name


class Util(object):

    @staticmethod
    def blits(destination_surface, source_surfaces, rect=None, blend_mode=0):
        for surface in source_surfaces:
            destination_surface.blit(surface[0], surface[1], rect, blend_mode)

    @staticmethod
    def length(v):
        return math.sqrt(v.x**2 + v.y**2 + v.z**2)

    @staticmethod
    def get_bounding_box(actor, offset_x=0, offset_y=0, scale_x=1,scale_y=1):
        bb = actor.trigger_volume.extent
        corners = [carla.Location(x=-bb.x*scale_x, y=-bb.y*scale_y),
                   carla.Location(x=bb.x*scale_x, y=-bb.y*scale_y),
                   carla.Location(x=bb.x*scale_x, y=bb.y*scale_y),
                   carla.Location(x=-bb.x*scale_x, y=bb.y*scale_y),
                   carla.Location(x=-bb.x*scale_x, y=-bb.y*scale_y)]
        corners = [carla.Location(x=offset_x,y=offset_y) + x + actor.trigger_volume.location for x in corners]
        t = actor.get_transform()
        t.transform(corners)
        return corners

# ==============================================================================
# -- ModuleManager -------------------------------------------------------------
# ==============================================================================


class ModuleManager(object):
    def __init__(self):
        self.modules = []

    def register_module(self, module):
        self.modules.append(module)

    def clear_modules(self):
        del self.modules[:]

    def tick(self, clock):
        # Update all the modules
        for module in self.modules:
            module.tick(clock)

    def render(self, display):
        display.fill(COLOR_ALUMINIUM_4)
        for module in self.modules:
            module.render(display)

    def get_module(self, name):
        for module in self.modules:
            if module.name == name:
                return module

    def start_modules(self):
        for module in self.modules:
            module.start()


# ==============================================================================
# -- FadingText ----------------------------------------------------------------
# ==============================================================================


class FadingText(object):
    def __init__(self, font, dim, pos):
        self.font = font
        self.dim = dim
        self.pos = pos
        self.seconds_left = 0
        self.surface = pygame.Surface(self.dim)

    def set_text(self, text, color=COLOR_WHITE, seconds=2.0):
        text_texture = self.font.render(text, True, color)
        self.surface = pygame.Surface(self.dim)
        self.seconds_left = seconds
        self.surface.fill(COLOR_BLACK)
        self.surface.blit(text_texture, (10, 11))

    def tick(self, clock):
        delta_seconds = 1e-3 * clock.get_time()
        self.seconds_left = max(0.0, self.seconds_left - delta_seconds)
        self.surface.set_alpha(500.0 * self.seconds_left)

    def render(self, display):
        return 
        display.blit(self.surface, self.pos)


# ==============================================================================
# -- HelpText ------------------------------------------------------------------
# ==============================================================================


class HelpText(object):
    def __init__(self, font, width, height):
        lines = __doc__.split('\n')
        self.font = font
        self.dim = (680, len(lines) * 22 + 12)
        self.pos = (0.5 * width - 0.5 * self.dim[0], 0.5 * height - 0.5 * self.dim[1])
        self.seconds_left = 0
        self.surface = pygame.Surface(self.dim)
        self.surface.fill(COLOR_BLACK)
        for n, line in enumerate(lines):
            text_texture = self.font.render(line, True, COLOR_WHITE)
            self.surface.blit(text_texture, (22, n * 22))
            self._render = False
        self.surface.set_alpha(220)

    def toggle(self):
        self._render = not self._render

    def render(self, display):
        return 
        if self._render:
            display.blit(self.surface, self.pos)


# ==============================================================================
# -- ModuleHUD -----------------------------------------------------------------
# ==============================================================================


class ModuleHUD (object):

    def __init__(self, name, width, height):
        self.name = name
        self.dim = (width, height)
        self._init_hud_params()
        self._init_data_params()

    def start(self):
        pass

    def _init_hud_params(self):
        fonts = [x for x in pygame.font.get_fonts()]
        default_font = 'ubuntumono'
        mono = default_font if default_font in fonts else fonts[0]
        mono = pygame.font.match_font(mono)
        self._font_mono = pygame.font.Font(mono, 14)
        self._header_font = pygame.font.SysFont('Arial', 14, True)
        self.help = HelpText(pygame.font.Font(mono, 24), *self.dim)
        self._notifications = FadingText(
            pygame.font.Font(pygame.font.get_default_font(), 20),
            (self.dim[0], 40), (0, self.dim[1] - 40))

    def _init_data_params(self):
        self.show_info = True
        self.show_actor_ids = False
        self._info_text = {}

    def notification(self, text, seconds=2.0):
        self._notifications.set_text(text, seconds=seconds)

    def tick(self, clock):
        self._notifications.tick(clock)

    def add_info(self, module_name, info):
        self._info_text[module_name] = info

    def render_vehicles_ids(self, vehicle_id_surface, list_actors, world_to_pixel, hero_actor, hero_transform):
        vehicle_id_surface.fill(COLOR_BLACK)
        if self.show_actor_ids:
            vehicle_id_surface.set_alpha(150)
            for actor in list_actors:
                x, y = world_to_pixel(actor[1].location)

                angle = 0
                if hero_actor is not None:
                    angle = -hero_transform.rotation.yaw - 90

                color = COLOR_SKY_BLUE_0
                if int(actor[0].attributes['number_of_wheels']) == 2:
                    color = COLOR_CHOCOLATE_0
                if actor[0].attributes['role_name'] == 'hero':
                    color = COLOR_CHAMELEON_0

                font_surface = self._header_font.render(str(actor[0].id), True, color)
                rotated_font_surface = pygame.transform.rotate(font_surface, angle)
                rect = rotated_font_surface.get_rect(center=(x, y))
                vehicle_id_surface.blit(rotated_font_surface, rect)

        return vehicle_id_surface

    def render(self, display):
        return 
        if self.show_info:
            info_surface = pygame.Surface((240, self.dim[1]))
            info_surface.set_alpha(100)
            display.blit(info_surface, (0, 0))
            v_offset = 4
            bar_h_offset = 100
            bar_width = 106
            i = 0
            for module_name, module_info in self._info_text.items():
                if not module_info:
                    continue
                surface = self._header_font.render(module_name, True, COLOR_ALUMINIUM_0).convert_alpha()
                display.blit(surface, (8 + bar_width / 2, 18 * i + v_offset))
                v_offset += 12
                i += 1
                for item in module_info:
                    if v_offset + 18 > self.dim[1]:
                        break
                    if isinstance(item, list):
                        if len(item) > 1:
                            points = [(x + 8, v_offset + 8 + (1.0 - y) * 30) for x, y in enumerate(item)]
                            pygame.draw.lines(display, (255, 136, 0), False, points, 1)
                        item = None
                    elif isinstance(item, tuple):
                        if isinstance(item[1], bool):
                            rect = pygame.Rect((bar_h_offset, v_offset + 8), (6, 6))
                            pygame.draw.rect(display, COLOR_ALUMINIUM_0, rect, 0 if item[1] else 1)
                        else:
                            rect_border = pygame.Rect((bar_h_offset, v_offset + 8), (bar_width, 6))
                            pygame.draw.rect(display, COLOR_ALUMINIUM_0, rect_border, 1)
                            f = (item[1] - item[2]) / (item[3] - item[2])
                            if item[2] < 0.0:
                                rect = pygame.Rect((bar_h_offset + f * (bar_width - 6), v_offset + 8), (6, 6))
                            else:
                                rect = pygame.Rect((bar_h_offset, v_offset + 8), (f * bar_width, 6))
                            pygame.draw.rect(display, COLOR_ALUMINIUM_0, rect)
                        item = item[0]
                    if item:  # At this point has to be a str.
                        surface = self._font_mono.render(item, True, COLOR_ALUMINIUM_0).convert_alpha()
                        display.blit(surface, (8, 18 * i + v_offset))
                    v_offset += 18
                v_offset += 24
        self._notifications.render(display)
        self.help.render(display)


# ==============================================================================
# -- TrafficLightSurfaces ------------------------------------------------------
# ==============================================================================

def get_edge_angle(wp1, wp2):
    roll1 = math.radians(wp1.transform.rotation.roll)
    pitch1 = math.radians(wp1.transform.rotation.pitch)
    yaw1 = math.radians(wp1.transform.rotation.yaw)
    
    cv1 = np.array([
        np.cos(yaw1)*np.cos(pitch1),
        np.sin(yaw1)*np.cos(pitch1),
        np.sin(pitch1)
    ])
    
    roll2 = math.radians(wp2.transform.rotation.roll)
    pitch2 = math.radians(wp2.transform.rotation.pitch)
    yaw2 = math.radians(wp2.transform.rotation.yaw)
    
    cv2 = np.array([
        np.cos(yaw2)*np.cos(pitch2),
        np.sin(yaw2)*np.cos(pitch2),
        np.sin(pitch2)
    ])
    
    deviation = math.acos(np.clip(
        np.dot(cv1, cv2)/(np.linalg.norm(cv1)*np.linalg.norm(cv2)), -1.0, 1.0))
    
    return deviation, np.cross(cv1, cv2)[2]


class TrafficLightSurfaces(object):
    """Holds the surfaces (scaled and rotated) for painting traffic lights"""

    def __init__(self):
        def make_surface(tl):
            w = 40
            surface = pygame.Surface((w, 3 * w), pygame.SRCALPHA)
            surface.fill(COLOR_ALUMINIUM_5 if tl != 'h' else COLOR_ORANGE_2)
            if tl != 'h':
                hw = int(w / 2)
                off = COLOR_ALUMINIUM_4
                red = COLOR_SCARLET_RED_0
                yellow = COLOR_BUTTER_0
                green = COLOR_CHAMELEON_0
                pygame.draw.circle(surface, red if tl == tls.Red else off, (hw, hw), int(0.4 * w))
                pygame.draw.circle(surface, yellow if tl == tls.Yellow else off, (hw, w + hw), int(0.4 * w))
                pygame.draw.circle(surface, green if tl == tls.Green else off, (hw, 2 * w + hw), int(0.4 * w))
            return pygame.transform.smoothscale(surface, (15, 45) if tl != 'h' else (19, 49))
        self._original_surfaces = {
            'h': make_surface('h'),
            tls.Red: make_surface(tls.Red),
            tls.Yellow: make_surface(tls.Yellow),
            tls.Green: make_surface(tls.Green),
            tls.Off: make_surface(tls.Off),
            tls.Unknown: make_surface(tls.Unknown)
        }
        self.surfaces = dict(self._original_surfaces)

    def rotozoom(self, angle, scale):
        for key, surface in self._original_surfaces.items():
            self.surfaces[key] = pygame.transform.rotozoom(surface, angle, scale)


# ==============================================================================
# -- World ---------------------------------------------------------------------
# ==============================================================================


class MapImage(object):
    def __init__(self, carla_world, carla_map, pixels_per_meter, show_triggers, show_connections, show_spawn_points, recompute=False):
        self._pixels_per_meter = pixels_per_meter
        self.scale = 1.0
        self.show_triggers = show_triggers
        self.show_connections = show_connections
        self.show_spawn_points = show_spawn_points

        waypoints = carla_map.generate_waypoints(2)
        margin = 50
        max_x = max(waypoints, key=lambda x: x.transform.location.x).transform.location.x + margin
        max_y = max(waypoints, key=lambda x: x.transform.location.y).transform.location.y + margin
        min_x = min(waypoints, key=lambda x: x.transform.location.x).transform.location.x - margin
        min_y = min(waypoints, key=lambda x: x.transform.location.y).transform.location.y - margin

        self.width = max(max_x - min_x, max_y - min_y)
        self._world_offset = (min_x, min_y)
        
        width_in_pixels = int(self._pixels_per_meter * self.width)

        self.big_map_surface = pygame.Surface((width_in_pixels, width_in_pixels)).convert()
        self.big_solid_lane_surface = pygame.Surface((width_in_pixels, width_in_pixels)).convert()
        self.big_broken_lane_surface = pygame.Surface((width_in_pixels, width_in_pixels)).convert()
        self.big_stop_surface = pygame.Surface((width_in_pixels, width_in_pixels)).convert()

        self.big_waypoint_surfaces = [pygame.Surface((width_in_pixels, width_in_pixels)).convert() for _ in range(6)]
        
        # Save static surfaces
        save_path = f'assets/big_maps/{carla_map.name}'
        if recompute:
            self.draw_road_map(
                    self.big_map_surface, self.big_solid_lane_surface, self.big_broken_lane_surface, self.big_stop_surface, self.big_waypoint_surfaces,
                    carla_world, carla_map, self.world_to_pixel, self.world_to_pixel_width)
        else:
            self.big_map_surface = pygame.image.load_extended(f'{save_path}/map.png')
            self.big_solid_lane_surface = pygame.image.load_extended(f'{save_path}/solid_lane.png')
            self.big_broken_lane_surface = pygame.image.load_extended(f'{save_path}/broken_lane.png')
            self.big_stop_surface = pygame.image.load_extended(f'{save_path}/stop.png')
            for i in range(6):
                self.big_waypoint_surfaces[i] = pygame.image.load_extended(f'{save_path}/waypoint{i}.png')
        
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        
        if recompute:
            pygame.image.save_extended(self.big_map_surface, f'{save_path}/map.png')
            pygame.image.save_extended(self.big_solid_lane_surface, f'{save_path}/solid_lane.png')
            pygame.image.save_extended(self.big_broken_lane_surface, f'{save_path}/broken_lane.png')
            pygame.image.save_extended(self.big_stop_surface, f'{save_path}/stop.png')
            for i in range(6):
                pygame.image.save_extended(self.big_waypoint_surfaces[i], f'{save_path}/waypoint{i}.png')

        self.map_surface = self.big_map_surface
        self.solid_lane_surface = self.big_solid_lane_surface
        self.broken_lane_surface = self.big_broken_lane_surface
        self.stop_surface = self.big_stop_surface
        self.waypoint_surfaces = self.big_waypoint_surfaces

        self.road_map = np.swapaxes(pygame.surfarray.array3d(self.big_map_surface),0,1)
        

    def draw_road_map(self, map_surface, solid_lane_surface, broken_lane_surface, stop_surface, waypoint_surfaces, carla_world, carla_map, world_to_pixel, world_to_pixel_width, threshold=math.radians(5)):
    # def draw_road_map(self, map_surface, carla_world, carla_map, world_to_pixel, world_to_pixel_width):
        """Draws all the roads, including lane markings, arrows and traffic signs"""
        # map_surface.fill(COLOR_ALUMINIUM_4)
        precision = 0.05
        map_surface.fill(COLOR_BLACK)
        solid_lane_surface.fill(COLOR_BLACK)
        broken_lane_surface.fill(COLOR_BLACK)

        def lane_marking_color_to_tango(lane_marking_color):
            """Maps the lane marking color enum specified in PythonAPI to a Tango Color"""
            tango_color = COLOR_BLACK

            if lane_marking_color == carla.LaneMarkingColor.White:
                tango_color = COLOR_ALUMINIUM_2

            elif lane_marking_color == carla.LaneMarkingColor.Blue:
                tango_color = COLOR_SKY_BLUE_0

            elif lane_marking_color == carla.LaneMarkingColor.Green:
                tango_color = COLOR_CHAMELEON_0

            elif lane_marking_color == carla.LaneMarkingColor.Red:
                tango_color = COLOR_SCARLET_RED_0

            elif lane_marking_color == carla.LaneMarkingColor.Yellow:
                tango_color = COLOR_ORANGE_0

            return tango_color

        def draw_solid_line(surface, color, closed, points, width):
            """Draws solid lines in a surface given a set of points, width and color"""
            if len(points) >= 2:
                pygame.draw.lines(surface, COLOR_WHITE, closed, points, width)

        def draw_broken_line(surface, color, closed, points, width):
            """Draws broken lines in a surface given a set of points, width and color"""
            # Select which lines are going to be rendered from the set of lines
            broken_lines = [x for n, x in enumerate(zip(*(iter(points),) * 20)) if n % 3 == 0]

            # Draw selected lines
            for line in broken_lines:
                pygame.draw.lines(surface, color, closed, line, width)

        def get_lane_markings(lane_marking_type, lane_marking_color, waypoints, sign):
            """For multiple lane marking types (SolidSolid, BrokenSolid, SolidBroken and BrokenBroken), it converts them
             as a combination of Broken and Solid lines"""
            margin = 0.25
            marking_1 = [world_to_pixel(lateral_shift(w.transform, sign * w.lane_width * 0.5)) for w in waypoints]
            if lane_marking_type == carla.LaneMarkingType.Broken or (lane_marking_type == carla.LaneMarkingType.Solid):
                return [(lane_marking_type, lane_marking_color, marking_1)]
            else:
                marking_2 = [world_to_pixel(lateral_shift(w.transform,
                                                          sign * (w.lane_width * 0.5 + margin * 2))) for w in waypoints]
                if lane_marking_type == carla.LaneMarkingType.SolidBroken:
                    return [(carla.LaneMarkingType.Broken, lane_marking_color, marking_1),
                            (carla.LaneMarkingType.Solid, lane_marking_color, marking_2)]
                elif lane_marking_type == carla.LaneMarkingType.BrokenSolid:
                    return [(carla.LaneMarkingType.Solid, lane_marking_color, marking_1),
                            (carla.LaneMarkingType.Broken, lane_marking_color, marking_2)]
                elif lane_marking_type == carla.LaneMarkingType.BrokenBroken:
                    return [(carla.LaneMarkingType.Broken, lane_marking_color, marking_1),
                            (carla.LaneMarkingType.Broken, lane_marking_color, marking_2)]
                elif lane_marking_type == carla.LaneMarkingType.SolidSolid:
                    return [(carla.LaneMarkingType.Solid, lane_marking_color, marking_1),
                            (carla.LaneMarkingType.Solid, lane_marking_color, marking_2)]

            return [(carla.LaneMarkingType.NONE, carla.LaneMarkingColor.Other, [])]

        def draw_lane(surface, lane, color):
            """Renders a single lane in a surface and with a specified color"""
            for side in lane:
                lane_left_side = [lateral_shift(w.transform, -w.lane_width * 0.5) for w in side]
                lane_right_side = [lateral_shift(w.transform, w.lane_width * 0.5) for w in side]

                polygon = lane_left_side + [x for x in reversed(lane_right_side)]
                polygon = [world_to_pixel(x) for x in polygon]

                if len(polygon) > 2:
                    pygame.draw.polygon(surface, color, polygon, 5)
                    pygame.draw.polygon(surface, color, polygon)

        def draw_lane_marking(solid_lane_surface, broken_lane_surface, waypoints):
            """Draws the left and right side of lane markings"""
            # Left Side
            draw_lane_marking_single_side(solid_lane_surface, broken_lane_surface, waypoints[0], -1)

            # Right Side
            draw_lane_marking_single_side(solid_lane_surface, broken_lane_surface, waypoints[1], 1)

        def draw_lane_marking_single_side(solid_lane_surface, broken_lane_surface, waypoints, sign):
            """Draws the lane marking given a set of waypoints and decides whether drawing the right or left side of
            the waypoint based on the sign parameter"""
            lane_marking = None

            marking_type = carla.LaneMarkingType.NONE
            previous_marking_type = carla.LaneMarkingType.NONE

            marking_color = carla.LaneMarkingColor.Other
            previous_marking_color = carla.LaneMarkingColor.Other

            markings_list = []
            temp_waypoints = []
            current_lane_marking = carla.LaneMarkingType.NONE
            for sample in waypoints:
                lane_marking = sample.left_lane_marking if sign < 0 else sample.right_lane_marking

                if lane_marking is None:
                    continue

                marking_type = lane_marking.type
                marking_color = lane_marking.color

                if current_lane_marking != marking_type:
                    # Get the list of lane markings to draw
                    markings = get_lane_markings(
                        previous_marking_type,
                        lane_marking_color_to_tango(previous_marking_color),
                        temp_waypoints,
                        sign)
                    current_lane_marking = marking_type

                    # Append each lane marking in the list
                    for marking in markings:
                        markings_list.append(marking)

                    temp_waypoints = temp_waypoints[-1:]

                else:
                    temp_waypoints.append((sample))
                    previous_marking_type = marking_type
                    previous_marking_color = marking_color

            # Add last marking
            last_markings = get_lane_markings(
                previous_marking_type,
                lane_marking_color_to_tango(previous_marking_color),
                temp_waypoints,
                sign)
            for marking in last_markings:
                markings_list.append(marking)

            # Once the lane markings have been simplified to Solid or Broken lines, we draw them
            for markings in markings_list:
                if markings[0] == carla.LaneMarkingType.Solid:
                    draw_solid_line(solid_lane_surface, markings[1], False, markings[2], 2)
                elif markings[0] == carla.LaneMarkingType.Broken:
                    # draw_broken_line(surface, markings[1], False, markings[2], 2)
                    draw_solid_line(broken_lane_surface, markings[1], False, markings[2], 2)

        def draw_arrow(surface, transform, color=COLOR_ALUMINIUM_2):
            """ Draws an arrow with a specified color given a transform"""
            transform.rotation.yaw += 180
            forward = transform.get_forward_vector()
            transform.rotation.yaw += 90
            right_dir = transform.get_forward_vector()
            end = transform.location
            start = end - 2.0 * forward
            right = start + 0.8 * forward + 0.4 * right_dir
            left = start + 0.8 * forward - 0.4 * right_dir

            # Draw lines
            pygame.draw.lines(surface, color, False, [world_to_pixel(x) for x in [start, end]], 4)
            pygame.draw.lines(surface, color, False, [world_to_pixel(x) for x in [left, start, right]], 4)

        def draw_traffic_signs(surface, actor):
            """Draw stop traffic signs and its bounding box if enabled"""
            pass

        def lateral_shift(transform, shift):
            transform.rotation.yaw += 90
            return transform.location + shift * transform.get_forward_vector()

        def draw_topology(carla_topology, index):
            """ Draws traffic signs and the roads network with sidewalks, parking and shoulders by generating waypoints"""
            topology = [x[index] for x in carla_topology]
            topology = sorted(topology, key=lambda w: w.transform.location.z)
            set_waypoints = []
            for waypoint in topology:
                waypoints = [waypoint]

                # Generate waypoints of a road id. Stop when road id differs
                nxt = waypoint.next(precision)
                if len(nxt) > 0:
                    nxt = nxt[0]
                    while nxt.road_id == waypoint.road_id:
                        waypoints.append(nxt)
                        nxt = nxt.next(precision)
                        if len(nxt) > 0:
                            nxt = nxt[0]
                        else:
                            break
                set_waypoints.append(waypoints)

                # Draw Shoulders, Parkings and Sidewalks
                PARKING_COLOR = COLOR_ALUMINIUM_4_5
                SHOULDER_COLOR = COLOR_ALUMINIUM_5
                SIDEWALK_COLOR = COLOR_ALUMINIUM_3

                shoulder = [[], []]
                parking = [[], []]
                sidewalk = [[], []]

                for w in waypoints:
                    # Classify lane types until there are no waypoints by going left
                    l = w.get_left_lane()
                    while l and l.lane_type != carla.LaneType.Driving:

                        if l.lane_type == carla.LaneType.Shoulder:
                            shoulder[0].append(l)

                        if l.lane_type == carla.LaneType.Parking:
                            parking[0].append(l)

                        if l.lane_type == carla.LaneType.Sidewalk:
                            sidewalk[0].append(l)

                        l = l.get_left_lane()

                    # Classify lane types until there are no waypoints by going right
                    r = w.get_right_lane()
                    while r and r.lane_type != carla.LaneType.Driving:

                        if r.lane_type == carla.LaneType.Shoulder:
                            shoulder[1].append(r)

                        if r.lane_type == carla.LaneType.Parking:
                            parking[1].append(r)

                        if r.lane_type == carla.LaneType.Sidewalk:
                            sidewalk[1].append(r)

                        r = r.get_right_lane()

                # Draw classified lane types
                # draw_lane(map_surface, shoulder, COLOR_WHITE)
                # draw_lane(map_surface, parking,  COLOR_WHITE)
                # draw_lane(map_surface, sidewalk, COLOR_WHITE)

            # Draw Roads
            for waypoints in set_waypoints:
                waypoint = waypoints[0]
                road_left_side = [lateral_shift(w.transform, -w.lane_width * 0.5) for w in waypoints]
                road_right_side = [lateral_shift(w.transform, w.lane_width * 0.5) for w in waypoints]

                polygon = road_left_side + [x for x in reversed(road_right_side)]
                polygon = [world_to_pixel(x) for x in polygon]

                if len(polygon) > 2:
                    pygame.draw.polygon(map_surface, COLOR_WHITE, polygon, 5)
                    pygame.draw.polygon(map_surface, COLOR_WHITE, polygon)

                # Draw Lane Markings and Arrows
                if not waypoint.is_junction:
                    draw_lane_marking(solid_lane_surface, broken_lane_surface, [waypoints, waypoints])
                #     for n, wp in enumerate(waypoints):
                #         if ((n + 1) % 400) == 0:
                #             draw_arrow(lane_surface, wp.transform)

        topology = carla_map.get_topology()
        draw_topology(topology, 0)
        draw_topology(topology, 1)

        # TODO: change map_surface to waypoint 
        if self.show_connections:
            dist = 2.0
            to_pixel = lambda wp: world_to_pixel(wp.transform.location)
            
            # Pass 1
            intersections = []
            for wp in carla_map.generate_waypoints(dist):
                if wp.is_junction:
                    intersections.append([wp.transform.location.x, wp.transform.location.y])

            intersections = np.array(intersections)
            for wp in carla_map.generate_waypoints(dist):
                
                wx, wy = wp.transform.location.x, wp.transform.location.y 
                
                next_wps = list(wp.next(dist))
                next_info = [get_edge_angle(wp, nwp) for nwp in next_wps]
                if len(next_info) == 0:
                    continue
                deviations, next_crosses = zip(*next_info)
                
                for nxt, deviation, next_cross in zip(next_wps, deviations, next_crosses):
                    
                    if deviation > math.radians(120):
                        continue
                    
                    nx, ny = nxt.transform.location.x, nxt.transform.location.y 
                    
                    dx = nx - wx
                    dy = ny - wy
                    
                    # if np.linalg.norm([dx,dy]) < 3.0:
                    #     continue
                    
                    angle = nxt.transform.rotation.yaw
                    col = encode_orientation(angle)
                        
                    # deviation, next_cross = get_edge_angle(wp, nxt)
                    
                    if np.min(np.linalg.norm(intersections-[wx, wy], axis=1)) > 0:
                        map_surfaces = [
                            waypoint_surfaces[RoadOption.LEFT.value-1],
                            waypoint_surfaces[RoadOption.RIGHT.value-1],
                            waypoint_surfaces[RoadOption.STRAIGHT.value-1],
                            waypoint_surfaces[RoadOption.LANEFOLLOW.value-1]
                        ]

                    elif next_cross < 0 and ((deviation > threshold) or (next_cross == min(next_crosses) and len(next_wps)>1)):
                        map_surfaces = [
                            waypoint_surfaces[RoadOption.LEFT.value-1],
                            waypoint_surfaces[RoadOption.LANEFOLLOW.value-1]
                        ]
                        
                        prev = nxt
                        while prev.is_junction:
                            best_cross = np.inf
                            for cur_candidate in prev.next(dist):
                                deviation, next_cross = get_edge_angle(prev, cur_candidate)
                                if next_cross < best_cross:
                                    cur = cur_candidate
                                    best_cross = next_cross

                            pygame.draw.line(waypoint_surfaces[RoadOption.LEFT.value-1], col, to_pixel(prev), to_pixel(cur), 1)
                            prev = cur

                    elif next_cross > 0 and ((deviation > threshold) or (next_cross == max(next_crosses) and len(next_wps)>1)):
                        map_surfaces = [
                            waypoint_surfaces[RoadOption.RIGHT.value-1],
                            waypoint_surfaces[RoadOption.LANEFOLLOW.value-1]
                        ]
                        
                        prev = nxt
                        while prev.is_junction:
                            best_cross = -np.inf
                            for cur_candidate in prev.next(dist):
                                deviation, next_cross = get_edge_angle(prev, cur_candidate)
                                if next_cross > best_cross:
                                    cur = cur_candidate
                                    best_cross = next_cross

                            pygame.draw.line(waypoint_surfaces[RoadOption.RIGHT.value-1], col, to_pixel(prev), to_pixel(cur), 1)
                            prev = cur
                    elif deviation <= threshold:
                        map_surfaces = [
                            waypoint_surfaces[RoadOption.STRAIGHT.value-1],
                            waypoint_surfaces[RoadOption.LANEFOLLOW.value-1]
                        ]
                    
                    # surface_maps[wp].append((nxt, map_surfaces))
                    for map_surface in map_surfaces:
                        pygame.draw.line(map_surface, col, to_pixel(wp), to_pixel(nxt), 1)

                if wp.lane_change & carla.LaneChange.Right:
                    # print ('LANE CHANGE RIGHT!')
                    r = wp.get_right_lane()
                    map_surface = waypoint_surfaces[RoadOption.CHANGELANERIGHT.value-1]
                    if r and r.lane_type == carla.LaneType.Driving:
                        nexts = r.next(dist)
                        if len(nexts) > 0:
                            r = nexts[0]
                            pygame.draw.line(map_surface, col, to_pixel(wp), to_pixel(r), 1)
                if wp.lane_change & carla.LaneChange.Left:
                    # print ('LANE CHANGE LEFT!')
                    l = wp.get_left_lane()
                    map_surface = waypoint_surfaces[RoadOption.CHANGELANELEFT.value-1]
                    if l and l.lane_type == carla.LaneType.Driving:
                        nexts = l.next(dist)
                        if len(nexts) > 0:
                            l = nexts[0]
                            pygame.draw.line(map_surface, col, to_pixel(wp), to_pixel(l), 1)
        
        # Draw stop sign box
        # TODO: yield?
        actors = carla_world.get_actors()
        stops = [actor for actor in actors if 'stop' in actor.type_id]
        for ts_stop in stops:
            draw_traffic_signs(stop_surface, ts_stop)

    def world_to_pixel(self, location, offset=(0,0)):
        x = self.scale * self._pixels_per_meter * (location.x - self._world_offset[0])
        y = self.scale * self._pixels_per_meter * (location.y - self._world_offset[1])
        return [int(x - offset[0]), int(y - offset[1])]

    def world_to_pixel_width(self, width):
        return int(self.scale * self._pixels_per_meter * width)

    def scale_map(self, scale):
        if scale != self.scale:
            self.scale = scale
            width = int(self.big_map_surface.get_width() * self.scale)
            self.surface = pygame.transform.smoothscale(self.big_map_surface, (width, width))


class ModuleWorld(object):
    # def __init__(self, name, args, timeout):
    def __init__(self, name, client, world, town_map, hero_actor, timeout=10):
        self.name = name
        self.timeout = timeout
        self.server_fps = 0.0
        self.simulation_time = 0
        self.server_clock = pygame.time.Clock()

        # World data
        self.client = client
        self.world = world
        self.town_map = town_map
        self.actors_with_transforms = []
        # Store necessary modules
        self.module_hud = None
        self.module_input = None

        self.surface_size = [0, 0]
        self.prev_scaled_size = 0
        self.scaled_size = 0
        # Hero actor
        self.hero_actor = hero_actor
        self.hero_transform = hero_actor.get_transform()
        
        # Hero actor bouding box
        self.hero_x = hero_actor.bounding_box.extent.x
        self.hero_y = hero_actor.bounding_box.extent.y

        self.scale_offset = [0, 0]

        self.vehicle_id_surface = None
        self.result_surface = None

        self.traffic_light_surfaces = TrafficLightSurfaces()
        self.affected_traffic_light = None

        # Map info
        self.map_image = None
        self.border_round_surface = None
        self.original_surface_size = None
        self.hero_surface = None
        self.actors_surface = None
        
        self.vehicle_surface = None
        self.walker_surface = None
        
        self.hero_map_surface = None
        self.hero_solid_lane_surface = None
        self.hero_broken_lane_surface = None
        self.hero_vehicle_surface = None
        self.hero_walker_surface = None
        self.hero_traffic_light_surface = None

        self.window_map_surface = None
        self.window_solid_lane_surface = None
        self.window_broken_lane_surface = None
        self.window_vehicle_surface = None
        self.window_walker_surface = None
        self.window_traffic_light_surface = None

        self.hero_map_image = None
        self.hero_lane_image = None
        self.hero_stop_image = None
        self.hero_vehicle_image = None
        self.hero_walker_image = None
        self.hero_traffic_image = None

    def get_rendered_surfaces(self):
        return (
            self.hero_map_image,
            self.hero_solid_lane_image,
            self.hero_broken_lane_image,
            self.hero_stop_image,
            self.hero_vehicle_image,
            self.hero_walker_image,
            self.hero_traffic_image,
            self.hero_waypoint_images,
        )

    def get_hero_measurements(self):
        pos = self.hero_actor.get_location()
        ori = self.hero_actor.get_transform().get_forward_vector()
        vel = self.hero_actor.get_velocity()
        acc = self.hero_actor.get_acceleration()

        return {
            'position': np.float32([pos.x, pos.y]),
            'orientation': np.float32([ori.x, ori.y]),
            'velocity': np.float32([vel.x, vel.y, vel.z]),
            'acceleration': np.float32([acc.x, acc.y, acc.z]),
        }

    def start(self, show_triggers=False,
                    show_connections=True,
                    show_spawn_points=False
        ):

        # Create Surfaces
        self.map_image = MapImage(
            carla_world=self.world,
            carla_map=self.town_map,
            pixels_per_meter=PIXELS_PER_METER,
            show_triggers=show_triggers,
            show_connections=show_connections,
            show_spawn_points=show_spawn_points)

        self.show_triggers = show_triggers
        self.show_connections = show_connections
        self.show_spawn_points = show_spawn_points

        # Store necessary modules
        self.module_hud = module_manager.get_module(MODULE_HUD)
        self.module_input = module_manager.get_module(MODULE_INPUT)

        self.window_width, self.window_height = MAP_SIZE, MAP_SIZE

        self.original_surface_size = min(self.module_hud.dim[0], self.module_hud.dim[1])
        self.surface_size = self.map_image.big_map_surface.get_width()

        self.scaled_size = int(self.surface_size)
        self.prev_scaled_size = int(self.surface_size)

        # Render Actors
        self.vehicle_surface = pygame.Surface((self.map_image.map_surface.get_width(), self.map_image.map_surface.get_height()))
        self.vehicle_surface.set_colorkey(COLOR_BLACK)
        self.self_surface = pygame.Surface((self.map_image.map_surface.get_width(), self.map_image.map_surface.get_height()))
        self.self_surface.set_colorkey(COLOR_BLACK)
        self.walker_surface = pygame.Surface((self.map_image.map_surface.get_width(), self.map_image.map_surface.get_height()))
        self.walker_surface.set_colorkey(COLOR_BLACK)
        self.traffic_light_surface = pygame.Surface((self.map_image.map_surface.get_width(), self.map_image.map_surface.get_height()))
        self.traffic_light_surface.set_colorkey(COLOR_BLACK)

        self.waypoint_surfaces = [
            pygame.Surface((self.map_image.map_surface.get_width(), self.map_image.map_surface.get_height()))
        for _ in range(6)]

        self.vehicle_id_surface = pygame.Surface((self.surface_size, self.surface_size)).convert()
        self.vehicle_id_surface.set_colorkey(COLOR_BLACK)

        self.border_round_surface = pygame.Surface(self.module_hud.dim, pygame.SRCALPHA).convert()
        self.border_round_surface.set_colorkey(COLOR_WHITE)
        self.border_round_surface.fill(COLOR_BLACK)

        center_offset = (int(self.module_hud.dim[0] / 2), int(self.module_hud.dim[1] / 2))
        pygame.draw.circle(self.border_round_surface, COLOR_ALUMINIUM_1, center_offset, int(self.module_hud.dim[1] / 2))
        pygame.draw.circle(self.border_round_surface, COLOR_WHITE, center_offset, int((self.module_hud.dim[1] - 8) / 2))
        
        scaled_original_size = self.original_surface_size
        # self.hero_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        
        self.hero_map_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_solid_lane_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_broken_lane_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_stop_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_vehicle_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_walker_surface = pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        self.hero_waypoint_surfaces = [
            pygame.Surface((scaled_original_size, scaled_original_size)).convert()
        for _ in range(6)]
        
        
        self.window_map_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_solid_lane_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_broken_lane_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_stop_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_vehicle_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_walker_surface = pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        self.window_waypoint_surfaces = [
            pygame.Surface((MAP_SIZE, MAP_SIZE)).convert()
        for _ in range(6)]
        
        self.result_surface = pygame.Surface((self.surface_size, self.surface_size)).convert()
        self.result_surface.set_colorkey(COLOR_BLACK)

        # Start hero mode by default
        self.module_input.wheel_offset = HERO_DEFAULT_SCALE
        self.module_input.control = carla.VehicleControl()

        self.road_map = self.map_image.road_map

        weak_self = weakref.ref(self)


    def tick(self, clock):
        actors = self.world.get_actors()
        self.actors_with_transforms = [(actor, actor.get_transform()) for actor in actors]
        if self.hero_actor is not None:
            self.hero_transform = self.hero_actor.get_transform()
        self.update_hud_info(clock)

    def update_hud_info(self, clock):
        hero_mode_text = []
        if self.hero_actor is not None:
            hero_speed = self.hero_actor.get_velocity()
            hero_speed_text = 3.6 * math.sqrt(hero_speed.x ** 2 + hero_speed.y ** 2 + hero_speed.z ** 2)

            affected_traffic_light_text = 'None'
            if self.affected_traffic_light is not None:
                state = self.affected_traffic_light.state
                if state == carla.TrafficLightState.Green:
                    affected_traffic_light_text = 'GREEN'
                elif state == carla.TrafficLightState.Yellow:
                    affected_traffic_light_text = 'YELLOW'
                else:
                    affected_traffic_light_text = 'RED'

            affected_speed_limit_text = self.hero_actor.get_speed_limit()

            hero_mode_text = [
                'Hero Mode:                 ON',
                'Hero ID:              %7d' % self.hero_actor.id,
                'Hero Vehicle:  %14s' % get_actor_display_name(self.hero_actor, truncate=14),
                'Hero Speed:          %3d km/h' % hero_speed_text,
                'Hero Affected by:',
                '  Traffic Light: %12s' % affected_traffic_light_text,
                '  Speed Limit:       %3d km/h' % affected_speed_limit_text
            ]
        else:
            hero_mode_text = ['Hero Mode:                OFF']

        self.server_fps = self.server_clock.get_fps()
        self.server_fps = 'inf' if self.server_fps == float('inf') else round(self.server_fps)
        module_info_text = [
            'Server:  % 16s FPS' % self.server_fps,
            'Client:  % 16s FPS' % round(clock.get_fps()),
            'Simulation Time: % 12s' % datetime.timedelta(seconds=int(self.simulation_time)),
            'Map Name:          %10s' % self.town_map.name,
        ]

        module_info_text = module_info_text
        module_hud = module_manager.get_module(MODULE_HUD)
        module_hud.add_info(self.name, module_info_text)
        module_hud.add_info('HERO', hero_mode_text)

    @staticmethod
    def on_world_tick(weak_self, timestamp):
        self = weak_self()
        if not self:
            return

        self.server_clock.tick()
        self.server_fps = self.server_clock.get_fps()
        self.simulation_time = timestamp.elapsed_seconds

    def _split_actors(self):
        vehicles = []
        traffic_lights = []
        speed_limits = []
        walkers = []

        for actor_with_transform in self.actors_with_transforms:
            actor = actor_with_transform[0]
            if 'vehicle' in actor.type_id or 'streetbarrier' in actor.type_id:
                vehicles.append(actor_with_transform)
            elif 'traffic_light' in actor.type_id:
                traffic_lights.append(actor_with_transform)
            elif 'speed_limit' in actor.type_id:
                speed_limits.append(actor_with_transform)
            elif 'pedestrian' in actor.type_id:
                walkers.append(actor_with_transform)

        info_text = []
        if self.hero_actor is not None and len(vehicles) > 1:
            location = self.hero_transform.location
            vehicle_list = [x[0] for x in vehicles if x[0].id != self.hero_actor.id]

            def distance(v): return location.distance(v.get_location())
            for n, vehicle in enumerate(sorted(vehicle_list, key=distance)):
                if n > 15:
                    break
                vehicle_type = get_actor_display_name(vehicle, truncate=22)
                info_text.append('% 5d %s' % (vehicle.id, vehicle_type))
        module_manager.get_module(MODULE_HUD).add_info(
            'NEARBY VEHICLES',
            info_text)

        return (vehicles, traffic_lights, speed_limits, walkers)

    def _render_traffic_lights(self, surface, list_tl, world_to_pixel, world_to_pixel_width):
        self.affected_traffic_light = None
        
        for tl in list_tl:
            
            world_pos = tl.get_location()
            pos = world_to_pixel(world_pos)

            if self.hero_actor is not None:
                corners = Util.get_bounding_box(tl)
                corners = [world_to_pixel(p) for p in corners]
                tl_t = tl.get_transform()

                transformed_tv = tl_t.transform(tl.trigger_volume.location)
                hero_location = self.hero_actor.get_location()
                d = hero_location.distance(transformed_tv)
                s = Util.length(tl.trigger_volume.extent) + Util.length(self.hero_actor.bounding_box.extent)
                if (d <= s):
                    # Highlight traffic light
                    self.affected_traffic_light = tl
                    srf = self.traffic_light_surfaces.surfaces['h']
                    surface.blit(srf, srf.get_rect(center=pos))

            srf = self.traffic_light_surfaces.surfaces[tl.state]
            surface.blit(srf, srf.get_rect(center=pos))



    def _render_speed_limits(self, surface, list_sl, world_to_pixel, world_to_pixel_width):

        font_size = world_to_pixel_width(2)
        radius = world_to_pixel_width(2)
        font = pygame.font.SysFont('Arial', font_size)

        for sl in list_sl:

            x, y = world_to_pixel(sl.get_location())

            # Render speed limit
            white_circle_radius = int(radius * 0.75)

            pygame.draw.circle(surface, COLOR_SCARLET_RED_1, (x, y), radius)
            pygame.draw.circle(surface, COLOR_ALUMINIUM_0, (x, y), white_circle_radius)

            limit = sl.type_id.split('.')[2]
            font_surface = font.render(limit, True, COLOR_ALUMINIUM_5)

            if self.show_triggers:
                corners = Util.get_bounding_box(sl)
                corners = [world_to_pixel(p) for p in corners]
                pygame.draw.lines(surface, COLOR_PLUM_2, True, corners, 2)

            # Blit
            if self.hero_actor is not None:
                # Rotate font surface with respect to hero vehicle front
                angle = -self.hero_transform.rotation.yaw - 90.0
                font_surface = pygame.transform.rotate(font_surface, angle)
                offset = font_surface.get_rect(center=(x, y))
                surface.blit(font_surface, offset)

            else:
                surface.blit(font_surface, (x - radius / 2, y - radius / 2))

    def _render_walkers(self, surface, list_w, world_to_pixel, world_to_pixel_width):
        ego_loc = self.hero_actor.get_location()
        for w in list_w:

            loc = w[0].get_location()
            dist = loc.distance(ego_loc)
            degree = 162 / (np.clip(dist, 1.5, 10.5)+0.3)
            world_pos = w[1].location
            
            if not self._is_point_on_sidewalk(world_pos, world_to_pixel) \
            and is_within_distance_ahead(w[0].get_transform(),
                                        self.hero_actor.get_transform(),
                                        20,
                                        degree=degree) \
            and abs(w[0].get_location().z - self.hero_actor.get_location().z) < 1:
            
                color = COLOR_WHITE
                bb = w[0].bounding_box.extent
    
                # corners = [
                #     carla.Location(x=-bb.x-1, y=-bb.y-1),
                #     carla.Location(x=bb.x+1, y=-bb.y-1),
                #     carla.Location(x=bb.x+1, y=bb.y+1),
                #     carla.Location(x=-bb.x-1, y=bb.y+1)]
    
                # w[1].transform(corners)
                # corners = [world_to_pixel(p) for p in corners]
                # pygame.draw.polygon(surface, color, corners)
                pos_x, pos_y =  world_to_pixel(w[1].location)
                radius = world_to_pixel_width(bb.x + 1)
                pygame.draw.circle(surface, color, (pos_x, pos_y), radius)

    def _is_point_on_sidewalk(self, loc, world_to_pixel):
        # Convert to pixel coordinate
        pixel_x, pixel_y = world_to_pixel(loc)
        pixel_y = np.clip(pixel_y, 0, self.road_map.shape[0]-1)
        pixel_x = np.clip(pixel_x, 0, self.road_map.shape[1]-1)
        point = self.road_map[pixel_y, pixel_x, 0]

        return np.all(point == 0)

    def _render_vehicles(self, surface, list_v, world_to_pixel):

        for v in list_v:
            # Do not render far away vehicles
            if v[0].get_location().distance(self.hero_actor.get_location()) > 40:
                continue
            
            # if 'role_name' in v[0].attributes and v[0].attributes['role_name'] == 'hero':
            #     continue

            color = COLOR_WHITE
            # Compute bounding box points
            if hasattr(v[0], 'bounding_box'):
                bb = v[0].bounding_box.extent
                corners = [
                    carla.Location(x=-bb.x, y=-bb.y),
                    carla.Location(x=-bb.x, y=bb.y),
                    carla.Location(x= bb.x, y=bb.y),
                    carla.Location(x= bb.x, y=-bb.y)
                ]

                v[1].transform(corners)
                corners = [world_to_pixel(p) for p in corners]
                pygame.draw.polygon(surface, color, corners)

    def render_actors(
            self, vehicle_surface, self_surface, walker_surface,
            traffic_light_surface, vehicles, traffic_lights,
            speed_limits, walkers
        ):
        # Static actors
        self._render_traffic_lights(traffic_light_surface, [tl[0] for tl in traffic_lights], self.map_image.world_to_pixel, self.map_image.world_to_pixel_width)

        # Dynamic actors
        self._render_vehicles(vehicle_surface, vehicles, self.map_image.world_to_pixel)
        self._render_walkers(walker_surface, walkers, self.map_image.world_to_pixel, self.map_image.world_to_pixel_width)

    def clip_surfaces(self, clipping_rect):
        self.vehicle_surface.set_clip(clipping_rect)
        self.walker_surface.set_clip(clipping_rect)
        self.traffic_light_surface.set_clip(clipping_rect)
        self.vehicle_id_surface.set_clip(clipping_rect)
        self.result_surface.set_clip(clipping_rect)
        [surface.set_clip(clipping_rect) for surface in self.waypoint_surfaces]

    def _compute_scale(self, scale_factor):
        m = self.module_input.mouse_pos

        # Percentage of surface where mouse position is actually
        px = (m[0] - self.scale_offset[0]) / float(self.prev_scaled_size)
        py = (m[1] - self.scale_offset[1]) / float(self.prev_scaled_size)

        # Offset will be the previously accumulated offset added with the
        # difference of mouse positions in the old and new scales
        diff_between_scales = ((float(self.prev_scaled_size) * px) - (float(self.scaled_size) * px),
                               (float(self.prev_scaled_size) * py) - (float(self.scaled_size) * py))

        self.scale_offset = (self.scale_offset[0] + diff_between_scales[0],
                             self.scale_offset[1] + diff_between_scales[1])

        # Update previous scale
        self.prev_scaled_size = self.scaled_size

        # Scale performed
        self.map_image.scale_map(scale_factor)

    def render(self, display):
        if self.actors_with_transforms is None:
            return
        self.result_surface.fill(COLOR_BLACK)
        vehicles, traffic_lights, speed_limits, walkers = self._split_actors()

        scale_factor = self.module_input.wheel_offset
        self.scaled_size = int(self.map_image.width * scale_factor)
        if self.scaled_size != self.prev_scaled_size:
            self._compute_scale(scale_factor)

        # Render Actors
        self.vehicle_surface.fill(COLOR_BLACK)
        self.walker_surface.fill(COLOR_BLACK)
        self.traffic_light_surface.fill(COLOR_BLACK)
        
        self.render_actors(
            self.vehicle_surface, self.self_surface, self.walker_surface,
            self.traffic_light_surface, vehicles, traffic_lights,
            speed_limits, walkers
        )
        
        # Render Ids
        self.module_hud.render_vehicles_ids(self.vehicle_id_surface, vehicles,
                                            self.map_image.world_to_pixel, self.hero_actor, self.hero_transform)

        # Blit surfaces
        surfaces = [(self.map_image.map_surface, (0, 0))]

        # surfaces = ((self.map_image.surface, (0, 0)),
        #             (self.actors_surface, (0, 0)),
        #             (self.vehicle_id_surface, (0, 0)),
        #             )

        angle = 0.0 if self.hero_actor is None else self.hero_transform.rotation.yaw + 90.0
        self.traffic_light_surfaces.rotozoom(0, self.map_image.scale)

        center_offset = (0, 0)
        if self.hero_actor is not None:

            hero_location_screen = self.map_image.world_to_pixel(self.hero_transform.location)
            hero_front = self.hero_transform.get_forward_vector()

            offset = [0, 0]
            offset[0] += hero_location_screen[0] - self.hero_map_surface.get_width() / 2
            offset[1] += hero_location_screen[1] - self.hero_map_surface.get_height() / 2

            offset[0] += hero_front.x * PIXELS_AHEAD_VEHICLE
            offset[1] += hero_front.y * PIXELS_AHEAD_VEHICLE

            # Apply clipping rect
            clipping_rect = pygame.Rect(offset[0],
                                        offset[1],
                                        self.hero_map_surface.get_width(),
                                        self.hero_map_surface.get_height())
            self.clip_surfaces(clipping_rect)
            self.border_round_surface.set_clip(clipping_rect)

            self.hero_map_surface.fill(COLOR_BLACK)
            self.hero_solid_lane_surface.fill(COLOR_BLACK)
            self.hero_broken_lane_surface.fill(COLOR_BLACK)
            self.hero_vehicle_surface.fill(COLOR_BLACK)
            self.hero_walker_surface.fill(COLOR_BLACK)
            [surface.fill(COLOR_BLACK) for surface in self.hero_waypoint_surfaces]

            self.hero_map_surface.blit(self.map_image.map_surface, (-offset[0], -offset[1]))
            self.hero_solid_lane_surface.blit(self.map_image.solid_lane_surface, (-offset[0], -offset[1]))
            self.hero_broken_lane_surface.blit(self.map_image.broken_lane_surface, (-offset[0], -offset[1]))
            self.hero_vehicle_surface.blit(self.vehicle_surface, (-offset[0], -offset[1]))
            self.hero_walker_surface.blit(self.walker_surface, (-offset[0], -offset[1]))
            [surface.blit(m_surface, (-offset[0], -offset[1])) for surface, m_surface in zip(self.hero_waypoint_surfaces, self.map_image.waypoint_surfaces)]

            # Rotate
            rotated_map_surface = pygame.transform.rotozoom(self.hero_map_surface, angle, 1.0).convert()
            rotated_solid_lane_surface = pygame.transform.rotozoom(self.hero_solid_lane_surface, angle, 1.0).convert()
            rotated_broken_lane_surface = pygame.transform.rotozoom(self.hero_broken_lane_surface, angle, 1.0).convert()
            rotated_vehicle_surface = pygame.transform.rotozoom(self.hero_vehicle_surface, angle, 1.0).convert()
            rotated_walker_surface = pygame.transform.rotozoom(self.hero_walker_surface, angle, 1.0).convert()
            rotated_waypoint_surfaces = [pygame.transform.rotozoom(surface, angle, 1.0).convert() for surface in self.hero_waypoint_surfaces]

            center = (display.get_width() / 2, display.get_height() / 2)
            rotation_map_pivot = rotated_map_surface.get_rect(center=center)
            rotation_solid_lane_pivot = rotated_solid_lane_surface.get_rect(center=center)
            rotation_broken_lane_pivot = rotated_broken_lane_surface.get_rect(center=center)
            rotation_vehicle_pivot = rotated_vehicle_surface.get_rect(center=center)
            rotation_walker_pivot = rotated_walker_surface.get_rect(center=center)
            rotation_waypoint_pivots = [surface.get_rect(center=center) for surface in rotated_waypoint_surfaces]

            self.window_map_surface.blit(rotated_map_surface, rotation_map_pivot)
            self.window_solid_lane_surface.blit(rotated_solid_lane_surface, rotation_solid_lane_pivot)
            self.window_broken_lane_surface.blit(rotated_broken_lane_surface, rotation_broken_lane_pivot)
            self.window_vehicle_surface.blit(rotated_vehicle_surface, rotation_vehicle_pivot)
            self.window_walker_surface.blit(rotated_walker_surface, rotation_walker_pivot)
            [w_surface.blit(r_surface, pivot) for w_surface, r_surface, pivot in zip(self.window_waypoint_surfaces, rotated_waypoint_surfaces, rotation_waypoint_pivots)]

            make_image = lambda x: np.swapaxes(pygame.surfarray.array3d(x), 0, 1)

            # Save surface as rgb array
            self.hero_map_image = make_image(self.window_map_surface).mean(axis=-1)
            self.hero_solid_lane_image = make_image(self.window_solid_lane_surface).mean(axis=-1)
            self.hero_broken_lane_image = make_image(self.window_broken_lane_surface).mean(axis=-1)
            self.hero_vehicle_image = make_image(self.window_vehicle_surface).mean(axis=-1)
            self.hero_walker_image = make_image(self.window_walker_surface).mean(axis=-1)
            self.hero_waypoint_images = [make_image(surface).mean(axis=-1) for surface in self.window_waypoint_surfaces]
        else:
            # Translation offset
            translation_offset = (self.module_input.mouse_offset[0] * scale_factor + self.scale_offset[0],
                                  self.module_input.mouse_offset[1] * scale_factor + self.scale_offset[1])
            center_offset = (abs(display.get_width() - self.surface_size) / 2 * scale_factor, 0)

            # Apply clipping rect
            clipping_rect = pygame.Rect(-translation_offset[0] - center_offset[0], -translation_offset[1],
                                        self.module_hud.dim[0], self.module_hud.dim[1])
            self.clip_surfaces(clipping_rect)
            Util.blits(self.result_surface, surfaces)

            display.blit(self.result_surface, (translation_offset[0] + center_offset[0],
                                               translation_offset[1]))

# ==============================================================================
# -- Input -----------------------------------------------------------
# ==============================================================================


class ModuleInput(object):
    def __init__(self, name):
        self.name = name
        self.mouse_pos = (0, 0)
        self.mouse_offset = [0.0, 0.0]
        self.wheel_offset = 0.1
        self.wheel_amount = 0.025
        self._steer_cache = 0.0
        self.control = None
        self._autopilot_enabled = False

    def start(self):
        hud = module_manager.get_module(MODULE_HUD)
        hud.notification("Press 'H' or '?' for help.", seconds=4.0)

    def render(self, display):
        pass

    def tick(self, clock):
        self.parse_input(clock)

    def _parse_events(self):
        self.mouse_pos = pygame.mouse.get_pos()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                exit_game()
            elif event.type == pygame.KEYUP:
                if self._is_quit_shortcut(event.key):
                    exit_game()
                elif event.key == K_h or (event.key == K_SLASH and pygame.key.get_mods() & KMOD_SHIFT):
                    module_hud = module_manager.get_module(MODULE_HUD)
                    module_hud.help.toggle()
                elif event.key == K_TAB:
                    module_world = module_manager.get_module(MODULE_WORLD)
                    module_hud = module_manager.get_module(MODULE_HUD)
                    if module_world.hero_actor is None:
                        module_world.select_hero_actor()
                        self.wheel_offset = HERO_DEFAULT_SCALE
                        self.control = carla.VehicleControl()
                        module_hud.notification('Hero Mode')
                    else:
                        self.wheel_offset = MAP_DEFAULT_SCALE
                        self.mouse_offset = [0, 0]
                        self.mouse_pos = [0, 0]
                        module_world.scale_offset = [0, 0]
                        module_world.hero_actor = None
                        module_hud.notification('Map Mode')
                elif event.key == K_F1:
                    module_hud = module_manager.get_module(MODULE_HUD)
                    module_hud.show_info = not module_hud.show_info
                elif event.key == K_i:
                    module_hud = module_manager.get_module(MODULE_HUD)
                    module_hud.show_actor_ids = not module_hud.show_actor_ids
                elif isinstance(self.control, carla.VehicleControl):
                    if event.key == K_q:
                        self.control.gear = 1 if self.control.reverse else -1
                    elif event.key == K_m:
                        self.control.manual_gear_shift = not self.control.manual_gear_shift
                        world = module_manager.get_module(MODULE_WORLD)
                        self.control.gear = world.hero_actor.get_control().gear
                        module_hud = module_manager.get_module(MODULE_HUD)
                        module_hud.notification('%s Transmission' % (
                            'Manual' if self.control.manual_gear_shift else 'Automatic'))
                    elif self.control.manual_gear_shift and event.key == K_COMMA:
                        self.control.gear = max(-1, self.control.gear - 1)
                    elif self.control.manual_gear_shift and event.key == K_PERIOD:
                        self.control.gear = self.control.gear + 1
                    elif event.key == K_p:
                        world = module_manager.get_module(MODULE_WORLD)
                        if world.hero_actor is not None:
                            self._autopilot_enabled = not self._autopilot_enabled
                            world.hero_actor.set_autopilot(self._autopilot_enabled)
                            module_hud = module_manager.get_module(MODULE_HUD)
                            module_hud.notification('Autopilot %s' % ('On' if self._autopilot_enabled else 'Off'))
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 4:
                    self.wheel_offset += self.wheel_amount
                    if self.wheel_offset >= 1.0:
                        self.wheel_offset = 1.0
                elif event.button == 5:
                    self.wheel_offset -= self.wheel_amount
                    if self.wheel_offset <= 0.1:
                        self.wheel_offset = 0.1

    def _parse_keys(self, milliseconds):
        keys = pygame.key.get_pressed()
        self.control.throttle = 1.0 if keys[K_UP] or keys[K_w] else 0.0
        steer_increment = 5e-4 * milliseconds
        if keys[K_LEFT] or keys[K_a]:
            self._steer_cache -= steer_increment
        elif keys[K_RIGHT] or keys[K_d]:
            self._steer_cache += steer_increment
        else:
            self._steer_cache = 0.0
        self._steer_cache = min(0.7, max(-0.7, self._steer_cache))
        self.control.steer = round(self._steer_cache, 1)
        self.control.brake = 1.0 if keys[K_DOWN] or keys[K_s] else 0.0
        self.control.hand_brake = keys[K_SPACE]

    def _parse_mouse(self):
        if pygame.mouse.get_pressed()[0]:
            x, y = pygame.mouse.get_pos()
            self.mouse_offset[0] += (1.0 / self.wheel_offset) * (x - self.mouse_pos[0])
            self.mouse_offset[1] += (1.0 / self.wheel_offset) * (y - self.mouse_pos[1])
            self.mouse_pos = (x, y)

    def parse_input(self, clock):
        self._parse_events()
        self._parse_mouse()
        if not self._autopilot_enabled:
            if isinstance(self.control, carla.VehicleControl):
                self._parse_keys(clock.get_time())
                self.control.reverse = self.control.gear < 0
            world = module_manager.get_module(MODULE_WORLD)
            if (world.hero_actor is not None):
                world.hero_actor.apply_control(self.control)

    @staticmethod
    def _is_quit_shortcut(key):
        return (key == K_ESCAPE) or (key == K_q and pygame.key.get_mods() & KMOD_CTRL)


# ==============================================================================
# -- Global Objects ------------------------------------------------------------
# ==============================================================================
module_manager = ModuleManager()


# ==============================================================================
# -- Wrap all this ----------------------------------------------------------------
# ==============================================================================
class Wrapper(object):
    clock = None
    display = None
    world_module = None
    pixels_per_meter = PIXELS_PER_METER
    
    @classmethod
    def init(cls, client, world, carla_map, player):
        os.environ['SDL_VIDEODRIVER'] = 'dummy'

        module_manager.clear_modules()

        pygame.init()
        display = pygame.display.set_mode((MAP_SIZE, MAP_SIZE), 0, 32)
        pygame.display.flip()

        # Set map drawer module
        input_module = ModuleInput(MODULE_INPUT)
        hud_module = ModuleHUD(MODULE_HUD, MAP_SIZE, MAP_SIZE)
        world_module = ModuleWorld(MODULE_WORLD, client, world, carla_map, player)

        # Register Modules
        module_manager.register_module(world_module)
        module_manager.register_module(hud_module)
        module_manager.register_module(input_module)
        module_manager.start_modules()

        cls.world_module = world_module
        cls.display = display
        cls.clock = pygame.time.Clock()

    @classmethod
    def tick(cls):
        module_manager.tick(cls.clock)
        module_manager.render(cls.display)

    @classmethod
    def get_observations(cls):
        road, solid_lane, broken_lane, stop, vehicle, pedestrian, traffic, waypoints = cls.world_module.get_rendered_surfaces()

        result = cls.world_module.get_hero_measurements()
        result.update({
            'road': np.uint8(road),
            'solid_lane': np.uint8(solid_lane),
            'broken_lane': np.uint8(broken_lane),
            'vehicle': np.uint8(vehicle),
            'pedestrian': np.uint8(pedestrian),
            'waypoints': np.uint8(waypoints),
        })

        # print (road.shape, lane.shape, stop.shape, vehicle.shape, pedestrian.shape, traffic.shape)

        pygame.display.flip()

        return result

    @classmethod
    def is_point_on_sidewalk(cls, pos):
        return cls.world_module._is_point_on_sidewalk(pos, cls.world_module.map_image.world_to_pixel)

    @staticmethod
    def clear():
        module_manager.clear_modules()

    @classmethod
    def render_world(cls):
        map_surface = cls.world_module.map_image.big_map_surface
        map_image = np.swapaxes(pygame.surfarray.array3d(map_surface), 0, 1)

        return map_image

    @classmethod
    def world_to_pixel(cls, pos):
        return cls.world_module.map_image.world_to_pixel(pos)